[project]
name = "pypodcastparser"
version = "0.1.0"
description = "Add your description here"
readme = ""
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.4",
]
